package scanner_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/ozgurcd/gograph/internal/scanner"
)

func TestShouldIgnoreDir(t *testing.T) {
	cases := []struct {
		dir    string
		expect bool
	}{
		{".git", true},
		{".gograph", true},
		{"vendor", true},
		{"node_modules", true},
		{"dist", true},
		{"build", true},
		{".terraform", true},
		{"internal", false},
		{"cmd", false},
		{"mypkg", false},
	}
	for _, tc := range cases {
		got := scanner.ShouldIgnoreDir(tc.dir)
		if got != tc.expect {
			t.Errorf("ShouldIgnoreDir(%q) = %v, want %v", tc.dir, got, tc.expect)
		}
	}
}

func TestShouldIgnoreFile_Suffixes(t *testing.T) {
	dir := t.TempDir()

	pb := filepath.Join(dir, "foo.pb.go")
	mustWrite(t, pb, "package foo\n")
	if skip, _ := scanner.ShouldIgnoreFile(pb); !skip {
		t.Error("expected .pb.go to be ignored")
	}

	gen := filepath.Join(dir, "bar_generated.go")
	mustWrite(t, gen, "package foo\n")
	if skip, _ := scanner.ShouldIgnoreFile(gen); !skip {
		t.Error("expected _generated.go to be ignored")
	}
}

func TestShouldIgnoreFile_CodeGeneratedComment(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "normal.go")
	mustWrite(t, path, "// Code generated by protoc. DO NOT EDIT.\npackage foo\n")
	if skip, _ := scanner.ShouldIgnoreFile(path); !skip {
		t.Error("expected file with 'Code generated' comment to be ignored")
	}
}

func TestShouldIgnoreFile_Normal(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "normal.go")
	mustWrite(t, path, "package foo\n\nfunc Hello() {}\n")
	if skip, _ := scanner.ShouldIgnoreFile(path); skip {
		t.Error("expected normal Go file not to be ignored")
	}
}

func TestWalk_SkipsIgnoredDirs(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, filepath.Join(root, "main.go"), "package main\nfunc main(){}\n")

	vendorDir := filepath.Join(root, "vendor", "pkg")
	if err := os.MkdirAll(vendorDir, 0o750); err != nil {
		t.Fatal(err)
	}
	mustWrite(t, filepath.Join(vendorDir, "vendor.go"), "package pkg\n")

	paths, errs := scanner.Walk(root)
	if len(errs) > 0 {
		t.Fatalf("unexpected errors: %v", errs)
	}
	if len(paths) != 1 {
		t.Fatalf("expected 1 path, got %d: %v", len(paths), paths)
	}
}

func mustWrite(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o640); err != nil {
		t.Fatal(err)
	}
}
